# Generated by Django 5.0 on 2023-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cadastro', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha1', models.CharField(max_length=70)),
                ('senha_2', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=255)),
                ('mensagem', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=1)),
                ('encerrado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatbotFinalizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=255)),
                ('mensagem', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=1)),
                ('encerrado', models.BooleanField(default=True)),
            ],
        ),
    ]
